### ISSUE TITLE
Do not show extra trains that go via airport [Feature request]

### ISSUE THREAD

**Issue by ykarikos** [ohanhi/trains#11]
Would it make sense to filter out trains that run on the ring track via airport for the ring track destinations that can be reached directly? E.g. for [Helsinki-Tapanila](https://trains.today/#/HKI/TNA), we get now P, I and N trains where I and N trains take 14 minutes for the journey and P trains 45 minutes (see attached image). Usually, it does not make any sense to take the P train, since it costs more and is slower.

The same applies for all ring track destinations besides Pasila and Airport. 
<img width="562" alt="screenshot 2019-01-18 at 23 27 39" src="https://user-images.githubusercontent.com/845477/51414443-35db4280-1b7b-11e9-969b-848fa35582cf.png">

Actually, I tried to create the filter by modifying `ringTrackFilterApplies`, but could not quite do it (yet). I've never done Elm before. :-D It would be nice to do this change as pair coding though.

**Comment by ohanhi** [comment]
Yes, this is a good question. I don't think filtering unconditionally is the best way to go. There's at least a couple of thigs to think about:

- In case the shorter route is no longer running (at night), you might want to take the longer route 
- From e.g. Aviapolis (and its neighboring stations) both directions take roughly the same amount of time but we would eliminate half the connections

Maybe this could be an option that is on by default and can be turned off?

**Comment by tuukka** [comment]
From a "going from A to B" point of view, this happens in the Espoo and Kerava directions as well: there are trains that leave later and arrive earlier, thus overtaking slower trains either physically or at least in the schedule.

From a journey planning point of view, there are at least 3 use cases to consider:
1. You want to be at the destination as soon as possible, be it with a faster train that leaves later or a slower train that leaves earlier. In this case, you can filter out any trains that will be overtaken by another.
2. You want to leave as soon as possible and don't care about the travel time. Say you're in Pasila in good time and want to board the first train that arrives (to sit down, to escape the winter weather, to charge your devices). In this case, you don't want any trains to be hidden from you.
3. Your schedule is flexible but you want to spend the least possible time in the train. In this case, you want to see only the fast routes (I to the airport, Z and R to Kerava, Y to Espoo) or at least to highlight them.

Some potential solutions:
1. Pick one of the use cases and leave the others to other services.
2. Provide an option or a button to switch between the use cases.
3. Make the cases visually apparent by highlighting them or including pictograms ("this is relatively slow", "this is the fastest"; I love how flight search services include warning pictograms for an overnight flight or a tight connection). E.g. https://matrix.itasoftware.com:
![screenshot from 2019-01-19 12-49-31-2x](https://user-images.githubusercontent.com/76985/51425750-e4699c80-1be8-11e9-8747-177519cecd1f.png)
4. Visualise the options on one axis and the times on another, making it apparent which ones leave earlier, arrive earlier or have the shortest duration. E.g. https://maps.google.com:
![screenshot from 2019-01-19 12-28-14-2x](https://user-images.githubusercontent.com/76985/51425614-44f7da00-1be7-11e9-8cc5-892d77338492.png)

Naturally, it depends on personal preferences as well.

**Comment by ohanhi** [comment]
Thanks for the input, Tuukka! As a quick gut feeling, the time axis visualization (option 4) looks great in that it shows the time dimension in a very glanceable way. Humans are very good at filtering information, providing it is glanceable, so we might not need any settings for this after all.

**Comment by ohanhi** [comment]
I did a quick sketch of how the [test data screenshot](https://github.com/ohanhi/trains/blob/master/tests/test-data-render.png) would look like this way. I'm not convinced. The information density I have on the current UI is pretty hard to accomplish with this approach.

![img_20190119_172804](https://user-images.githubusercontent.com/8436403/51428794-96688f00-1c10-11e9-83a8-2bd25e4d3059.jpg)

**Comment by ykarikos** [comment]
> Yes, this is a good question. I don't think filtering unconditionally is the best way to go. There's at least a couple of thigs to think about:
> 
> * In case the shorter route is no longer running (at night), you might want to take the longer route
> * From e.g. Aviapolis (and its neighboring stations) both directions take roughly the same amount of time but we would eliminate half the connections
> 
> Maybe this could be an option that is on by default and can be turned off?

Good points. For me, this kind of option would be quite optimal.

**Comment by ohanhi** [comment]
Do you think a visualization like this would help?

![screenshot from 2019-01-21 12-59-12](https://user-images.githubusercontent.com/8436403/51470463-a00f0580-1d7c-11e9-82e2-e22e35023a10.png)

**Comment by tuukka** [comment]
I think the bars were nice for glanceability, but I see you removed them from the code afterwards. Were they too much a disruption from the layout flow?

**Comment by ohanhi** [comment]
They felt very invasive for cases where the durations aren't very different (most cases?). Also, I'm not sure if it is very intuitive to look at a bar like that and go "oh, this card's top bar is almost full width, let me see if I can find a shorter one". 

I'll keep thinking about this idea, but for now I feel like the Kehärata filter (with toggle) is a reasonable solution for the issue presented.

**Comment by petja** [comment]
Simplicity of the app is important to me, so I'm not sure about moving metadata to the top and adding duration bars under it. These bars which might be unclear to users who haven't read this thread. 

I'm thinking about just sorting trains by their arrival time on the destination station. Similarly as the itinerary suggestions of [HSLdevcom/digitransit-ui](https://github.com/HSLdevcom/digitransit-ui).

**Comment by ohanhi** [comment]
What precisely do you find more difficult than before? Maybe this can be made better. 

Also, could you in the future try and empathize a little bit more with the people who make free apps or libraries for you to enjoy. "What initially drew my attention..." and "I would consider ... rollback" can be seen as a rather hostile way to communicate your point of view and I have to say I did (and do) feel bad after reading the comment.

**Comment by tuukka** [comment]
@petja Thanks for filling in a potential solution that I forgot to consider! Sorting by arrival time at destination would help my use case 1 and perhaps 3 as well without making 2 impossible indeed, but on the other hand it wouldn't be a clean solution to any of these. For example, in use case 1, how would you find the second best train if you couldn't make it to the first one?

However, now that I think of it, perhaps the setting in #21 could be replaced by dimming the trains that are going to be overtaken by a later one? Then it would be up to you to take one anyway (use case 2) or skip them (use case 1 & 3). This could be considered as a variant of solution 3.

**Comment by petja** [comment]
@ohanhi Sorry for my bad word choices and feeling they produced. By saying "what initially drew my attention" I meant to just open the discussion and tell what made me to use the app on the first place, but probably using past tense made comment look like I wouldn't use app anymore – which is of course not the case. "Rollback" was purely bad, sorry for that again. I'm taking my lesson. Thanks for pointing out these, I didn't see these as hostile when I wrote them.

Moving metadata to the top was probably my issue. And the bars under it could be unclear to users who haven't read this thread.

**Comment by ohanhi** [comment]
Let me shed some light into my thoughts:
- My own stations are such that all trains are roughly the same, so none of this data matters to me personally. I prefer not to see unnecessary data.
- Kehärata is different from normal tracks. People commuting from e.g. Tapanila or Malminkartano to Pasila or Helsinki do not expect or want to see the trains that go the "long way". For them, trains via the Airport can be considered unnecessary data.
- On normal tracks where a slower train is overtaken by a faster one, it depends on the use case what the user might want to see. I don't like the idea of sorting by arrival time, since I think of this as a departure station schedule screen (that only shows trains I could take). Also, dimming would reduce visual contrast and thus make it harder for low vision users to use the app.

Taking all this into account, I think I will remove the duration bars and numbers. I am visioning a notification text, shown only if the train would be overtaken by a later one. 

Just to make it clear, I am not looking to support all use cases in an optimal way. A half-way solution (like the one I made) is likely to be worse for everyone, and adding more and more settings is not a road I want to take either.

**Comment by petja** [comment]
Well reasoned. Sorting by arrival time has its problems if you're looking for trains departuring later than now, indeed.

Also, I really appreciate you want to keep things high contrast and thus respect people with low vision. Unfortunately this isn't prioritized thing at all on the most of the apps yet in 2019.
