### ISSUE TITLE
Omitting non-stopping stations

### ISSUE THREAD

**Issue by petja** [ohanhi/trains#17]
Considering this app is mostly for non railway enthusiastic people, should we omit non-stopping and track switching stations? These might be confusing for Average Joe.

## Examples

**P train**

❌ _On time in Virkamies_
✅ _On time between Aviapolis-Airport_

**R train**

❌ _2 minutes late in Kuurila_
✅ _2 minutes late between Toijala-Iittala_

**Comment by ohanhi** [comment]
Yes, this makes sense to me. The proposed format does have the potential for very large variation in length, but let me meditate on this for a while.
