### ISSUE TITLE
Delayed trains are not in the order of arrival

### ISSUE THREAD

**Issue by ykarikos** [ohanhi/trains#27]
When trains are delayed they might run in different order than their scheduled order. It would be more convenient to show them ordered by their actual predicted arrival time. See attached image

![Screenshot_20190827-075743~2](https://user-images.githubusercontent.com/845477/63771936-c41d6100-c8e0-11e9-9ead-1830ff116b97.png)

And, once again, huge thanks and props for this awesome service Ossi! <3

**Comment by ohanhi** [comment]
Personally I prefer that the trains do not swap positions on the listing, even if the estimated times made them arrive in a different order. So I am not sure which one is "the way" to go. Also worth noting: the current (scheduled time as the sorting criterion) also works when some trains are cancelled and don't have an estimate.

**Comment by ykarikos** [comment]
It is indeed nice that the cancelled trains are shown at the expected departure time on the list. Thus, for consistent user experience, it probably makes sense to have the delayed trains too like they are now. Maybe the "real-life expected departure time sorting" might work as a configuration option.

Anyways, I'm not disagreeing with you, so I'll close the issue. Thanks for commenting!
