### ISSUE TITLE
Display track number [Feature request]

### ISSUE THREAD

**Issue by olpeh** [ohanhi/trains#3]
Hi, would it be possible to display the track number? 
That is the only feature that keeps me from using this and using junat.net at the moment.

I might be interested in creating a PR about this if the information is available via the API

**Comment by ohanhi** [comment]
@olpeh Track number is now visible next to the station name. :+1:

**Comment by olpeh** [comment]
Thanks a lot @ohanhi :jolt: :1st_place_medal:
